### ISSUE TITLE
Provide mechanism to add custom rules

### ISSUE THREAD

**Issue by gimmeshelter** [koajs/parameter#13]
There is currently no way to use the full power of parameter and add custom rules when using koa-parameter.  I suggest either letting the user pass in their own pre-initialized and setup Parameter object or giving some config option to add custom rules.

**Comment by vnues** [comment]
> There is currently no way to use the full power of parameter and add custom rules when using koa-parameter. I suggest either letting the user pass in their own pre-initialized and setup Parameter object or giving some config option to add custom rules.

you can use `joi`

**Comment by gimmeshelter** [comment]
> > There is currently no way to use the full power of parameter and add custom rules when using koa-parameter. I suggest either letting the user pass in their own pre-initialized and setup Parameter object or giving some config option to add custom rules.
> 
> you can use `joi`

You’re right and we already switched.  Much happier.
