### ISSUE TITLE
Translate error message

### ISSUE THREAD

**Issue by anolek** [koajs/parameter#8]
Hi,

Maybe i miss something, but i didn't find anything to translate error message from this module :(

Since the version 1.1.1 of parameter, we can pass a function to translate all the error message. 
Is it possible to upgrade parameter to this version (or last version), and expose "parameter.translate" (or something else like `parameter(app, translate)` please ? :)

I can send a PR if you want

Thanks !

**Comment by fengmk2** [comment]
pr welcome :)
